### ISSUE TITLE
Adding maintainers / transferring ownership

### ISSUE THREAD

**Issue by rwwagner90** [peopledoc/ember-metrics-pendo#14]
Hi @GreatWizard thanks for this addon! There are a few stale PRs, and it seems CI is broken. Perhaps we should add some new maintainers or transfer this addon to https://github.com/adopted-ember-addons so more people can help work on it?

**Comment by GreatWizard** [comment]
Hello @rwwagner90;

Right now we are still taking care of this addon and we are still using it in all our apps.
I'm taking a look about the broken CI.

There is no need to transfer it to adopted-ember-addons yet and we are definitively open to contribution :)

**Comment by GreatWizard** [comment]
I detect that fork PRs wasn't run by our CI.
I update the configuration if you rebase your PR and repush it all will be fine :+1:
